'use client';

import Hamburger from '@/components/hamburger/hamburger';
import Search from '@/components/search/search';
import { Inter } from 'next/font/google';
import Link from 'next/link';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
// 	title: 'Create Next App',
// 	description: 'Generated by create next app',
// };

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body>
				<div className='bg-slate-900 flex justify-between ml  text-neutral-500 text-lg items-center'>
					<div className='flex ml-5 text-white'>
						<Hamburger />
					</div>
					<div className=' text-neutral-500 text-lg'>
						<Link
							className='ml-5 hover:text-red-300 transition-all'
							href='/home'
						>
							Главная
						</Link>
						<Link className='ml-5 hover:text-red-300 ' href='/home'>
							Сериалы
						</Link>
						<Link className='ml-5' href='/home'>
							Фильмы
						</Link>
						<Link className='ml-5' href='/home'>
							Мультфильмы
						</Link>
						<Link className='ml-5' href='/home'>
							Турецкие сериалы
						</Link>
						<Link className='ml-5' href='/home'>
							Дорамы
						</Link>
					</div>
					<div className='flex'>
						<Search />
						<span className='ml-5'>Войти</span>
					</div>
				</div>
				{children}
			</body>
		</html>
	);
}
